### ISSUE TITLE
Blue borders with sanityinc-tomorrow-blue on emacs client

### ISSUE THREAD

**Issue by Postroutine** [purcell/color-theme-sanityinc-tomorrow#104] opened 2018-01-30 10:55 UTC
If I use sanityinc-tomorrow-blue theme and restart my emacs daemon, all emacs clients have blue borders on the left and right of their frame. I need to set the theme again to fix that (until I restart my emacs daemon).

**Comment by drot** [comment] 2018-01-30 11:53
Yeah, related to #100

**Comment by purcell** [comment] 2018-02-04 22:02
Thanks. Closing as duplicate of #100.

**Closed by purcell** 2018-02-04 22:02 UTC
